fail-fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        entry: poetry run ruff
        language: system
    -   id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
    -   id: black
        name: black
        entry: poetry run black --check
        language: system
    -   id: isort
        entry: poetry run isort --check
        name: isort
        language: system
